### PR TITLE
Added rolling category to updater

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by mimi89999** [comment]
@pgaskin Did you have time to look at this?

**Comment by pgaskin** [comment]
I won't have time until next week (I've been busy with my username change and some of my other projects).

**Comment by mimi89999** [comment]
@pgaskin When will you have time to look at this? More than a month ago you suggested that you will look at is a week later...

**Comment by mimi89999** [comment]
Thanks a lot for reviewing this! Could you please also look at my other updater PRs?

**Pull request merged**
